### ISSUE TITLE
How to remove Task ?

### ISSUE THREAD

**Issue by henrylu** [nodeca/idoit#23]
In order to save the capacity of redis, I need to delete the task that has been successfully run, but it seems that there is no method such as task.remove or queue.remove(taskId) in the api to call, only find a setDeadline, can setDeadline (0) delete all data of task in redis ? or would you add remove method ?

**Comment by puzrin** [comment]
https://github.com/nodeca/idoit#registertaskoptions-registertaskname--cron-process

See `.track`. Que has gc.

I'd suggest to inspect code, if you wish to dive deep.
